// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwG_So3LaD01Y6nrXPPwBYra_EpCpVnp8',
    appId: '1:714337731386:web:341e59f655b02dd132c603',
    messagingSenderId: '714337731386',
    projectId: 'to-do-application-fda24',
    authDomain: 'to-do-application-fda24.firebaseapp.com',
    storageBucket: 'to-do-application-fda24.appspot.com',
    measurementId: 'G-VZMDSHP00M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGODEWHrslG79iP2Xq2sLFGn0jG0KE9qI',
    appId: '1:714337731386:android:650145e722a3ff2432c603',
    messagingSenderId: '714337731386',
    projectId: 'to-do-application-fda24',
    storageBucket: 'to-do-application-fda24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbjmvI0-v5i-PpbnO-WkU6wNAiiYiW8T0',
    appId: '1:714337731386:ios:10df46ae06cd36e432c603',
    messagingSenderId: '714337731386',
    projectId: 'to-do-application-fda24',
    storageBucket: 'to-do-application-fda24.appspot.com',
    iosBundleId: 'com.example.toDoApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbjmvI0-v5i-PpbnO-WkU6wNAiiYiW8T0',
    appId: '1:714337731386:ios:e3ee70cd524a337432c603',
    messagingSenderId: '714337731386',
    projectId: 'to-do-application-fda24',
    storageBucket: 'to-do-application-fda24.appspot.com',
    iosBundleId: 'com.example.toDoApplication.RunnerTests',
  );
}
